### ISSUE TITLE
S40 thermostat doesn't work

### ISSUE THREAD

**Issue by curta21** [akgoode/homebridge-lennox-icomfort#2]
Hello,

I just got a s40 thermostat installed and I guess they removed HomeKit support from it that the s30 had for some reason. When I tried this I get "unauthorized" loop. The app for the s40 is using lennoxicomfort.com not myicomfort.com. I am wondering if this is the issue. Please let me know what info you need to hopefully implement the new s40 thermostat. Thank you!

**Comment by akgoode** [comment]
Hi, apologies for the delay in getting back to you.  That is precisely the reason why that is happening.  Like I wrote to other user who left a comment, I don't have those thermostats so it is a little difficult to test.

Additionally, it will be a little trial and error to make sure that the APIs at the different urls are the same and function the same as the ones for the wifi thermostat.

**Comment by curta21** [comment]
I am happy to help if you want to implement this as I think Lennox has migrated to these thermostats for new installs. Please let me know what I can do to help if you would like. If not I totally understand. Thank you!

**Comment by gtg450g** [comment]
I have both an S30 and an S40 and would be happy to help as well because I’d really like the S40 to be in the Home app!

**Comment by BioTech2000** [comment]
Any update on the S40? I really don't want to use home assistant

**Comment by gtg450g** [comment]
Same here!
ᐧ

**Comment by akgoode** [comment]
> Any update on the S40? I really don't want to use home assistant

Unfortunately it won't be possible for me to make any other kind of thermostats work.  The package that this app depends on doesn't know the format of the API for other thermostats so I can't connect it.  If that existed, I could.  Its also harder to test without those thermostats in my house.
